### ISSUE TITLE
Latest version of CLO

### ISSUE THREAD

**Issue by twhetzel** [CLO-ontology/CLO#66]
Hi @yongqunh - where is the latest version of CLO maintained? I see in the CLO repo [1] the latest commit is from Dec. 22, 2020, but OntoBee shows a version from 2019-02-10 [2]. 

Is CLO still actively maintained or was it subsumed by another project?

[1] https://github.com/CLO-ontology/CLO/blob/master/src/ontology/clo.owl
[2] http://www.ontobee.org/ontology/clo

**Comment by yongqunh** [comment]
Hi Trish, the CLO is still actively maintained. It is not actively developed due to our busy schedule in the last couple of years of the COVID-19 pandemic. 

The final ontology should be the merged version as shown here:
https://github.com/CLO-ontology/CLO/blob/master/src/ontology/clo_merged.owl

I will check this out more later. Thanks!

**Comment by yongqunh** [comment]
These should be solved now. Thanks!
